version: '3'
services:
  frontend:
    build: ./frontend19v
    ports:
      - "9998:8080"
  backend:
    build: ./BackEnd19v
    ports:
      - "9990:8080"
  fuseki:
    image: stain/jena-fuseki
    ports:
      - "3030:3030"
  mongo:
    image: mongo
    ports:
      - "27020:27017"